DROP TABLE IF EXISTS questions CASCADE;
CREATE TABLE questions (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  exam_id INTEGER REFERENCES exams(id) ON DELETE CASCADE,
  question VARCHAR(1000) NOT NULL,
  question_option TEXT NOT NULL,
  answer VARCHAR(255) NOT NULL,
  feedback VARCHAR(2000) NOT NULL
);
